version: '3'
services:
        cgit_srv:
                build: .
                ports:
                        - 8181:80
                volumes:
                        - /srv/git:/srv/git
                        - ./default.conf:/etc/nginx/sites-available/default
                        - ./cgitrc:/etc/cgitrc
